-- =========================================
-- FUNDING DATA IMPORT SQL
-- Generated: 2025-12-22T04:09:47.867Z
-- Non-dilutive records: 83
-- Equity records: 90
-- Total: 173
-- =========================================

-- STEP 1: Delete existing data
DELETE FROM funding_opportunities;
DELETE FROM upcoming_opportunities;

-- STEP 2: Insert non-dilutive funding (83 records)
INSERT INTO funding_opportunities (
  name, opportunity_type, check_size, location, deadline,
  focus_areas, description, website, link, featured
) VALUES
(
    '1871/Bunker Labs Veteran Accelerator',
    'Accelerator',
    'Program value ~$20K',
    'Chicago, IL',
    'Bi-annual',
    ARRAY['All sectors'],
    'Veteran and military spouse founders | Free accelerator, no equity taken, veteran-focused',
    'https://www.bunkerlabs.org/',
    'https://www.bunkerlabs.org/',
    true
  ),
(
    'AWS Activate',
    'Credits',
    'Up to $100K AWS credits',
    'Global',
    'Rolling',
    ARRAY['Cloud','Infrastructure'],
    'VC-backed or accelerator-backed startups | AWS credits, technical training, no equity',
    'https://aws.amazon.com/activate/',
    'https://aws.amazon.com/activate/',
    true
  ),
(
    'Duality Accelerator',
    'Grant',
    'Varies (18 grants listed)',
    'Chicago-preferred',
    'Rolling',
    ARRAY['Impact','Underrepresented founders'],
    'Diverse founders, underrepresented entrepreneurs | Focus on diverse founders',
    'https://www.dualityaccelerator.com/',
    'https://www.dualityaccelerator.com/',
    true
  ),
(
    'Entrepreneurial Equity Initiative',
    'Grant',
    '$10K grants',
    'Chicago-area',
    'Annual',
    ARRAY['Black','Latinx founders'],
    'Black and Latinx entrepreneurs in Chicago | Chicago-specific, JPMorgan Chase program',
    'https://www.jpmorgan.com/',
    'https://www.jpmorganchase.com/impact/our-approach/racial-equity',
    true
  ),
(
    'Evergreen Climate Innovations',
    'Grant',
    '$150K-$500K',
    'Chicago, IL (HQ or expansion)',
    'Rolling',
    ARRAY['Climate','Clean energy','Carbon removal'],
    'Climate tech startups with measurable carbon impact | Focus on climate solutions with deployment strategy',
    'http://evergreeninno.org',
    'http://evergreeninno.org',
    true
  ),
(
    'Google for Startups Cloud Program',
    'Credits',
    'Up to $200K Google Cloud credits',
    'Global',
    'Rolling',
    ARRAY['Cloud','AI','Mobile'],
    'Early-stage startups using or building on Google Cloud | GCP credits, technical support, no equity',
    'https://cloud.google.com/startup',
    'https://cloud.google.com/startup',
    true
  ),
(
    'Landis Family Fellow by mHUB',
    'Fellowship',
    '$50K + resources',
    'Chicago, IL',
    'Quarterly',
    ARRAY['Hardtech','Physical products','Manufacturing'],
    'Hardtech entrepreneurs with technical innovation | Fellowship includes funding, workspace, mentorship',
    'https://mhubchicago.com',
    'https://mhubchicago.com/landis-family-fellow/',
    true
  ),
(
    'Microsoft for Startups Founders Hub',
    'Credits',
    'Up to $150K Azure credits + $1K+ in tools',
    'Global',
    'Rolling',
    ARRAY['Cloud','AI','Enterprise software'],
    'Seed-stage startups, B2B focus preferred | Azure credits, GitHub Enterprise, OpenAI API access',
    'https://www.microsoft.com/startups',
    'https://www.microsoft.com/startups',
    true
  ),
(
    'SBIR Phase I - DOD',
    'Grant',
    'Up to $200K',
    'US-based',
    'Rolling',
    ARRAY['Defense','Dual-use tech','Innovation'],
    'Small businesses (<500 employees) with R&D focus. US ownership required | Non-dilutive R&D funding, no IP surrender',
    'https://www.sbir.gov/',
    'https://www.sbir.gov/',
    true
  ),
(
    'SBIR Phase I - DOE',
    'Grant',
    'Up to $250K',
    'US-based',
    'Windows open 2x/year',
    ARRAY['Energy','Climate','Clean tech'],
    'Energy and climate tech startups with R&D | Energy-focused R&D, strong climate tech emphasis',
    'https://www.energy.gov/sbir/',
    'https://www.energy.gov/sbir/',
    true
  ),
(
    'SBIR Phase I - NIH',
    'Grant',
    'Up to $400K',
    'US-based',
    'Windows open 3x/year',
    ARRAY['HealthTech','BioTech','Medical devices'],
    'Health and life sciences startups with R&D focus | Life sciences R&D, higher award amounts than other agencies',
    'https://sbir.nih.gov/',
    'https://sbir.nih.gov/',
    true
  ),
(
    'SBIR Phase I - NSF',
    'Grant',
    'Up to $275K',
    'US-based',
    'Windows open quarterly',
    ARRAY['DeepTech','Science','Engineering'],
    'Deep tech startups with NSF-relevant research | Most founder-friendly SBIR program, no matching required',
    'https://seedfund.nsf.gov/',
    'https://seedfund.nsf.gov/',
    true
  ),
(
    'The Raise by LongJump',
    'Grant',
    '$10K (5 winners)',
    'Chicago, IL',
    'March 2026',
    ARRAY['Pre-seed preparation','All sectors'],
    'Post-product, pre-pre-seed Chicago founders planning to fundraise. Raised <$100K dilutive capital, building <1 year | 6-part workshop series (Jan 20 - Mar 11, 2026). Includes pitch deck development, investor matchmaking',
    'https://longjump.vc',
    'https://tally.so/r/3XKDdg',
    true
  ),
(
    'VentureCat Northwestern 2026',
    'Competition',
    '$75000+ prizes',
    'Chicago, IL',
    'April 9 2026',
    ARRAY['Student-led ventures'],
    'Student entrepreneurs | Application window March 30-April 9 2026, Finals May 27 2026, workshops and prep April-May, Northwestern students',
    'https://www.venturecat.northwestern.edu/schedule-key-dates/',
    'https://www.venturecat.northwestern.edu/schedule-key-dates/',
    true
  ),
(
    'mPOWER by mHUB',
    'Grant',
    '$50K',
    'Chicago, IL',
    'Rolling',
    ARRAY['Hardtech','DeepTech','Manufacturing'],
    'Early-stage hardtech and deeptech startups | Non-dilutive grant for product development',
    'https://mhubchicago.com',
    'https://mhubchicago.com/mpower/',
    true
  ),
(
    '43North',
    'Competition',
    '$1M grand prize + $500K runner-up',
    'Buffalo, NY (relocation required)',
    'Annual',
    ARRAY['All sectors'],
    'High-growth startups willing to relocate to Buffalo | Largest startup prize in US, requires Buffalo relocation',
    'https://www.43north.org/',
    'https://www.43north.org/apply/',
    false
  ),
(
    'AAUW Career Development Grants',
    'Grant',
    'Up to $8000',
    'US-based',
    'Dec 31 2025',
    ARRAY['Women in STEM careers leadership/executive training'],
    'Individual professionals | U.S. citizens/permanent residents with bachelor''s degree, 400+ instructional hours programs',
    'https://www.aauw.org/',
    'https://www.aauw.org/',
    false
  ),
(
    'Amber Grant',
    'Grant',
    '$10K monthly, $25K annual',
    'US, Canada',
    'Monthly',
    ARRAY['All sectors (women founders)'],
    'Women-owned businesses | Women-only, monthly $10K + annual $25K awards',
    'https://ambergrantsforwomen.com/',
    'https://ambergrantsforwomen.com/',
    false
  ),
(
    'Amber Grant for Women',
    'Grant',
    '$10000 monthly + $25000 year-end (3 winners)',
    'Global',
    'Monthly (last day of month 11:59 PM ET)',
    ARRAY['Monthly themed categories (Nov: STEM Dec: Fashion Jan: Skilled Trades)'],
    'Women-owned businesses | One application enters monthly + year-end consideration, women over 18, 50%+ women-owned, startups eligible',
    'https://ambergrantsforwomen.com/',
    'https://ambergrantsforwomen.com/',
    false
  ),
(
    'American Family Institute Innovation Grant',
    'Grant',
    'Up to $50K',
    'US-based',
    'Annual',
    ARRAY['InsurTech'],
    'InsurTech and related technology startups | InsurTech specific, American Family partnership opportunities',
    'https://www.amfam.com/',
    'https://institute.amfam.com/',
    false
  ),
(
    'American Underground - Launch Challenge',
    'Grant',
    '$10K-$25K',
    'North Carolina',
    'Quarterly',
    ARRAY['All sectors'],
    'Early-stage startups in the Southeast | Southeast regional, NC-based',
    'https://www.americanunderground.com/',
    'https://www.americanunderground.com/',
    false
  ),
(
    'Arch Grants',
    'Grant',
    '$50K equity-free',
    'St. Louis, MO (relocation required)',
    'Annual',
    ARRAY['All sectors'],
    'Early-stage startups willing to relocate to St. Louis | Highly competitive, requires 1-year St. Louis commitment',
    'https://archgrants.org/',
    'https://archgrants.org/apply/',
    false
  ),
(
    'Awesome Foundation',
    'Grant',
    '$1000 monthly',
    'Global',
    'Rolling basis',
    ARRAY['Projects with awesome ideas (not limited to businesses)'],
    'All stages | 84 independently run chapters worldwide, trustees fund grants, encourage any great idea',
    'https://www.awesomefoundation.org/',
    'https://www.awesomefoundation.org/',
    false
  ),
(
    'Backstage Capital Accelerator',
    'Accelerator',
    '$100K + program',
    'Los Angeles, CA',
    'Annual',
    ARRAY['Underrepresented founders','All sectors'],
    'Underrepresented founders (women, POC, LGBTQ+) | Takes equity but critical resource for underrepresented founders',
    'https://backstagecapital.com/',
    'https://backstagecapital.com/',
    false
  ),
(
    'Baylor New Venture Competition - Round 2',
    'Competition',
    '$200000+ cash + in-kind',
    'Global',
    'Jan 19 2026',
    ARRAY['All sectors global'],
    'University students/alumni | Top 50 submit full business plan, Finals March 27-28 2026, partnered with National Collegiate Innovation Championship',
    'https://hankamer.baylor.edu/baugh-center/new-venture',
    'https://hankamer.baylor.edu/baugh-center/new-venture',
    false
  ),
(
    'Capital One Business Grants',
    'Grant',
    'Varies, typically $25K',
    'US-based',
    'Annual',
    ARRAY['Underrepresented founders','All sectors'],
    'Small businesses, focus on underrepresented founders | Corporate grant program, underrepresented founder focus',
    'https://www.capitalone.com/',
    'https://www.capitalone.com/',
    false
  ),
(
    'Cartier Women''s Initiative',
    'Grant',
    '$100K + mentorship',
    'Global',
    'Annual',
    ARRAY['Women founders','Impact'],
    'Women-led businesses with social/environmental impact | Global women''s entrepreneurship award, impact focus',
    'https://www.cartierwomensinitiative.com/',
    'https://www.cartierwomensinitiative.com/',
    false
  ),
(
    'Chicago Innovation Exchange Accelerator',
    'Accelerator',
    '$10K-$25K prizes',
    'Chicago-connected',
    'Annual',
    ARRAY['All sectors'],
    'UChicago-affiliated founders and students | University of Chicago entrepreneurship hub, multiple programs',
    'https://polsky.uchicago.edu/',
    'https://polsky.uchicago.edu/',
    false
  ),
(
    'CodeLaunch USA 2026',
    'Competition',
    '$50k+ investment + services',
    'Global',
    'Feb 1 2026',
    ARRAY['US-based founders'],
    'Early-stage | Finals April 15 2026 Miami, World Championship Nov 11 2026, applications open Oct 15 2025',
    'https://codelaunch.com/events/2026-usa/',
    'https://codelaunch.com/events/2026-usa/',
    false
  ),
(
    'Dream Big Competition (BMO)',
    'Competition',
    '$50K + prizes',
    'Chicago-area',
    'Annual',
    ARRAY['High school students','Chicago'],
    'Students in Chicago Public Schools with business ideas | High school competition, Chicago-focused',
    'https://www.bmoharris.com/',
    'https://www.bmoharris.com/main/business/dream-big/',
    false
  ),
(
    'EDA Disaster Supplemental - Industry Transformation',
    'Grant',
    'Part of $1.45B disaster recovery',
    'Global',
    'March 3 2026',
    ARRAY['Disaster recovery (hurricanes wildfires floods tornadoes 2023-2024)'],
    'Community/Regional | American communities with major disaster declarations, Readiness grants on rolling basis',
    'https://www.eda.gov/',
    'https://www.eda.gov/',
    false
  ),
(
    'EDA Tech Hubs - Stage II',
    'Grant',
    'Part of $220M funding',
    'US-based',
    'Feb 18 2026',
    ARRAY['Critical technologies regional tech hubs'],
    'Regional development | U.S. Economic Development Administration, Stage I deadline was Nov 7 2025, support American regions as global tech leaders',
    'https://www.eda.gov/',
    'https://www.eda.gov/',
    false
  ),
(
    'EIC Accelerator Step 2 - 1st Cutoff 2026',
    'Grant',
    'Up to €2.5M grant, up to €15M equity',
    'Global',
    'Jan 7 2026',
    ARRAY['Deep Technology'],
    'Early to Growth | European funding, multiple cutoffs throughout 2026, Step 1 rolling',
    'https://eic.ec.europa.eu/',
    'https://eic.ec.europa.eu/',
    false
  ),
(
    'EIC Accelerator Step 2 - 2nd Cutoff 2026',
    'Grant',
    'Up to €2.5M grant, up to €15M equity',
    'Global',
    'March 4 2026',
    ARRAY['Deep Technology'],
    'Early to Growth | European funding, SMEs and startups, transformational R&D commercialization potential',
    'https://eic.ec.europa.eu/',
    'https://eic.ec.europa.eu/',
    false
  ),
(
    'Earth Rising Foundation Grants',
    'Grant',
    '$2500-$40000',
    'US-based',
    'Dec 31 2025',
    ARRAY['Climate crisis awareness Indigenous voices regenerative agriculture social justice'],
    'Nonprofits/Organizations | U.S.-based organizations, priority to Indigenous voices, youth activism, sustainable visions',
    'https://www.earthrisingfoundation.org/',
    'https://www.earthrisingfoundation.org/',
    false
  ),
(
    'Elevate Ventures - Community Ideation Fund',
    'Grant',
    '$2K-$10K',
    'Indiana',
    'Rolling',
    ARRAY['All sectors'],
    'Indiana residents with early-stage ideas | Indiana-only pre-revenue grant',
    'https://elevateventures.com/',
    'https://elevateventures.com/apply/',
    false
  ),
(
    'Elevate Ventures - Pre-Seed Accelerator Fund',
    'Grant',
    'Up to $75K (50% grant, 50% convertible)',
    'Indiana',
    'Quarterly',
    ARRAY['All sectors'],
    'Indiana startups, post-revenue preferred | Hybrid grant/convertible structure',
    'https://elevateventures.com/',
    'https://elevateventures.com/apply/',
    false
  ),
(
    'Faire Small Business Grant',
    'Grant',
    '$5000 in Faire.com credit',
    'US-based',
    'Dec 31 2025',
    ARRAY['New retail businesses'],
    'Early-stage retail | U.S.-based, opened within last year or opening this year, 6-month use window for credit',
    'https://www.faire.com/',
    'https://www.faire.com/',
    false
  ),
(
    'Fast Forward Nonprofit Accelerator',
    'Grant',
    '$15K + $100K in tech credits',
    'US-based',
    'Annual',
    ARRAY['Impact tech nonprofits'],
    'Tech nonprofits using tech for social impact | For registered nonprofits only, tech for good focus',
    'https://www.ffwd.org/',
    'https://www.ffwd.org/apply/',
    false
  ),
(
    'FedEx Small Business Grant',
    'Grant',
    '$50K grand prize + others',
    'US-based',
    'Annual (Spring)',
    ARRAY['All sectors'],
    'Small businesses with compelling stories | Public voting component, marketing value for participants',
    'https://www.fedex.com/',
    'https://www.fedex.com/smallbusinessgrant/',
    false
  ),
(
    'Forum Ventures - Launch',
    'Accelerator',
    'Varies',
    'Global',
    'Rolling',
    ARRAY['B2B SaaS','Marketplace','FinTech'],
    'Pre-seed/Seed',
    'https://www.launch.co/',
    'https://www.launch.co/',
    false
  ),
(
    'Freed Fellowship',
    'Grant',
    '$500 monthly + $2500 year-end eligibility',
    'US-based',
    'Monthly rolling (last day)',
    ARRAY['All sectors'],
    'Small businesses | U.S.-based small business owners, expert feedback included, must win monthly to be eligible for year-end',
    'https://www.freedfellowship.com/',
    'https://www.freedfellowship.com/',
    false
  ),
(
    'Global Insurance Accelerator 2026',
    'Accelerator',
    '$50000 for 5% equity',
    'Global',
    'Sept 19 2025 (for 2026 cohort)',
    ARRAY['InsurTech (underwriting claims customer engagement automation)'],
    'Early-stage | 15-week hybrid program, 75+ mentors, Des Moines Iowa, present at Global Insurance Symposium, 100-day program',
    'https://www.globalinsuranceaccelerator.com/',
    'https://www.globalinsuranceaccelerator.com/',
    false
  ),
(
    'Halcyon Incubator',
    'Accelerator',
    '$10K stipend + housing + program',
    'Washington DC',
    'Annual',
    ARRAY['Social impact'],
    'Social entrepreneurs addressing social issues | Residential fellowship in DC, impact-focused',
    'https://www.halcyonhouse.org/',
    'https://www.halcyonhouse.org/',
    false
  ),
(
    'Heartland Challenge',
    'Competition',
    '$250K grand prize',
    'Midwest',
    'Annual',
    ARRAY['All sectors'],
    'Midwest startups with scalable solutions | Midwest regional competition, various prize tiers',
    'https://www.heartlandchallenge.com/',
    'https://www.heartlandchallenge.com/',
    false
  ),
(
    'Hello Tomorrow Global Challenge',
    'Competition',
    '€1M+ in prizes',
    'Global',
    'Annual',
    ARRAY['DeepTech'],
    'DeepTech startups solving global challenges | Global deep tech competition, Paris final',
    'https://hello-tomorrow.org/',
    'https://hello-tomorrow.org/global-challenge/',
    false
  ),
(
    'Illinois SBDC - Innovation Voucher',
    'Grant',
    'Up to $15K',
    'Illinois',
    'Rolling',
    ARRAY['All sectors'],
    'Illinois small businesses needing R&D support | Voucher for university research partnerships, Illinois-only',
    'https://dceo.illinois.gov/',
    'https://dceo.illinois.gov/',
    false
  ),
(
    'Inc.U Competition (Invent Penn State)',
    'Competition',
    'Up to $30000',
    'Global',
    'Jan 18 2026',
    ARRAY['Student-led startups USA'],
    'Undergraduate students | Applications open Jan 12 2026, live final event March 21 2026, undergraduate-led only',
    'https://invent.psu.edu/programs/inc-u-competition/',
    'https://invent.psu.edu/programs/inc-u-competition/',
    false
  ),
(
    'Lake Forest College Venture Design Challenge 2026',
    'Competition',
    '$10000+ prizes',
    'Chicago area',
    'Feb 13 2026',
    ARRAY['All sectors'],
    'College students | Finals April 26 2026, workshops and mentorship included, Lake Forest College students and alumni',
    'https://www.lakeforest.edu/academics/majors-and-minors/entrepreneurship-and-innovation/venture-design-challenge',
    'https://www.lakeforest.edu/academics/majors-and-minors/entrepreneurship-and-innovation/venture-design-challenge',
    false
  ),
(
    'LaunchKC Grants — 2026 Cohort',
    'Grant',
    '$50K',
    'Kansas City, MO (engagement required)',
    'Q1 2026',
    ARRAY['B2B SaaS'],
    'B2B/SaaS startups willing to engage with KC ecosystem | Requires Kansas City engagement/relocation, highly competitive',
    'https://www.launchkc.org/',
    'https://www.launchkc.org/',
    false
  ),
(
    'MassChallenge Chicago',
    'Accelerator',
    '$0 equity, $1M+ in prizes',
    'Global (Chicago program)',
    'Annual',
    ARRAY['All sectors'],
    'High-impact startups, all stages | Zero-equity accelerator, top performers win cash prizes',
    'https://masschallenge.org/',
    'https://masschallenge.org/',
    false
  ),
(
    'MassChallenge HealthTech',
    'Accelerator',
    '$0 equity, $350K+ in prizes',
    'Global',
    'Annual',
    ARRAY['HealthTech'],
    'Digital health and healthcare innovation startups | Health-specific cohort, zero equity model',
    'https://masschallenge.org/',
    'https://masschallenge.org/programs-healthtech',
    false
  ),
(
    'Moderne Passport',
    'Accelerator',
    'Varies',
    'Global',
    'Nov 21, 2026',
    ARRAY['PropTech','InsurTech','FinTech'],
    'Early-stage | 6-month program, exclusive network access',
    'https://www.moderneventures.com/passport',
    'https://www.moderneventures.com/passport',
    false
  ),
(
    'Moderne Passport Industry Immersion',
    'Accelerator',
    '6-month immersion, network access',
    'Global',
    'Rolling',
    ARRAY['PropTech','InsurTech','FinTech'],
    'PropTech, InsurTech, FinTech, Real Estate Tech startups | Customer access program, exclusive network introductions',
    'https://www.moderneventures.com/',
    'https://www.moderneventures.com/passport',
    false
  ),
(
    'NASE Growth Grants',
    'Grant',
    'Varies',
    'Global',
    'Quarterly (Jan Apr Jul Oct)',
    ARRAY['Business growth/development (marketing equipment)'],
    'Small businesses | Must be NASE member, applications reviewed quarterly, for established businesses',
    'https://www.nase.org/',
    'https://www.nase.org/',
    false
  ),
(
    'NIST MEP',
    'Grant',
    'Varies by state, up to $50K cost-share',
    'US-based',
    'Rolling',
    ARRAY['Manufacturing'],
    'Manufacturing companies, hardtech startups | Manufacturing extension partnership, state-by-state programs',
    'https://www.nist.gov/mep',
    'https://www.nist.gov/mep',
    false
  ),
(
    'NSF I-Corps',
    'Grant',
    '$50K + training',
    'US-based',
    'Rolling cohorts',
    ARRAY['DeepTech','University spin-outs'],
    'NSF-funded researchers, SBIR/STTR awardees, deep tech founders | Lean LaunchPad methodology, customer discovery training',
    'https://www.nsf.gov/',
    'https://www.nsf.gov/icorps/',
    false
  ),
(
    'Opportunity Fund',
    'Grant',
    '$2.6K-$100K loans + grants',
    'CA, NV',
    'Rolling',
    ARRAY['Underrepresented founders','All sectors'],
    'Low-income entrepreneurs, especially minorities | Microloans not grants, but critical for underserved founders',
    'https://www.opportunityfund.org/',
    'https://www.opportunityfund.org/',
    false
  ),
(
    'P33 Chicago Civic Innovation Challenge',
    'Competition',
    'Varies, typically $50K-$100K',
    'Chicago',
    'Annual',
    ARRAY['Civic tech'],
    'Tech solutions for civic challenges in Chicago | Chicago-specific civic innovation, partnership opportunities',
    'https://www.p33chicago.com/',
    'https://www.p33chicago.com/',
    false
  ),
(
    'PitchBook University Innovation Prize',
    'Competition',
    '$50K grand prize',
    'Any university student',
    'Annual',
    ARRAY['All sectors'],
    'University students with innovative business ideas | National student competition, university affiliation required',
    'https://pitchbook.com/',
    'https://pitchbook.com/',
    false
  ),
(
    'Render Capital',
    'Grant',
    'Varies',
    'Louisville, KY',
    'Rolling',
    ARRAY['B2B SaaS'],
    'B2B/SaaS startups | Mixed grants and non-dilutive funding',
    'https://www.rendercapital.com/',
    'https://airtable.com/appQUVdAGKT1Xlbpw/shrfETcyF3ChKnnVP',
    false
  ),
(
    'Rice Business Plan Competition',
    'Competition',
    '$1M+ in prizes',
    'Any university student',
    'Annual',
    ARRAY['All sectors'],
    'University students with business plans | Richest graduate-level business plan competition, April annually',
    'https://rbpc.rice.edu/',
    'https://rbpc.rice.edu/',
    false
  ),
(
    'SBIR Phase I - NASA',
    'Grant',
    'Up to $150K',
    'US-based',
    'Windows open annually',
    ARRAY['Space','Aerospace','Advanced materials'],
    'Space tech, aerospace, advanced materials startups | Space and aerospace innovation, dual-use encouraged',
    'https://sbir.nasa.gov/',
    'https://sbir.nasa.gov/',
    false
  ),
(
    'SBIR Phase I - USDA',
    'Grant',
    'Up to $175K',
    'US-based',
    'Windows open annually',
    ARRAY['AgTech','Food','Rural innovation'],
    'Agriculture, food tech, rural innovation startups | Agriculture and food systems innovation',
    'https://www.nifa.usda.gov/sbir',
    'https://www.nifa.usda.gov/sbir',
    false
  ),
(
    'STTR Phase I (All Agencies)',
    'Grant',
    'Similar to SBIR (varies by agency)',
    'US-based',
    'Varies by agency',
    ARRAY['All SBIR sectors'],
    'Small businesses partnering with research institutions | Requires partnership with university/research institution, similar to SBIR',
    'https://www.sbir.gov/',
    'https://www.sbir.gov/',
    false
  ),
(
    'Slauson & Co - Friends & Family',
    'Accelerator',
    'Varies',
    'Global',
    'Rolling',
    ARRAY['B2B/SaaS','Fintech'],
    'Pre-seed | LA-based, remote-friendly',
    'https://c9dk4mvfi53.typeform.com/to/X9xmDDcg',
    'https://c9dk4mvfi53.typeform.com/to/X9xmDDcg',
    false
  ),
(
    'South Summit Startup Competition - Madrid',
    'Competition',
    'Prize + investment opportunities',
    'Global',
    'Jan 31 2026',
    ARRAY['Innovation across all sectors'],
    'All stages | 50 finalists pitch at event, Madrid June 4-6 2026, mentoring exposure networking included',
    'https://www.southsummit.co/',
    'https://www.southsummit.co/',
    false
  ),
(
    'Space Symposium Innovate Pitch Competition',
    'Competition',
    'Consulting + industry exposure prizes',
    'Global',
    'Jan 15 2026',
    ARRAY['Space aerospace defense'],
    'Early-stage | Global startups in space sector, pitch in April 2026 at Space Symposium Colorado Springs',
    'https://www.spacesymposium.org/innovate-pitch-competition/',
    'https://www.spacesymposium.org/innovate-pitch-competition/',
    false
  ),
(
    'SparkWV - Round 2',
    'Competition',
    'Prize money TBD',
    'Global',
    'Jan 31 2026',
    ARRAY['All sectors West Virginia'],
    'Student entrepreneurs | Finalists notified Feb 20 2026, final presentations March 23 2026, must use VentureDash portal',
    'https://www.edvgroup.org/',
    'https://www.edvgroup.org/',
    false
  ),
(
    'Start.Pivot.Grow',
    'Grant',
    '$2500 + business planning tools',
    'Global',
    'Quarterly',
    ARRAY['All sectors'],
    'Small businesses | In business 2+ years, 1-2 employees including owner, $50k+ annual revenue',
    'https://www.startpivotgrow.com/',
    'https://www.startpivotgrow.com/',
    false
  ),
(
    'Startmate (Australia/NZ)',
    'Accelerator',
    '$75000 for 7.5% equity',
    'Global',
    'Jan 31 2026',
    ARRAY['All sectors'],
    'Early-stage | 12-week program, Australia/New Zealand focus, strong community network to scale globally',
    'https://www.startmate.com/',
    'https://www.startmate.com/',
    false
  ),
(
    'Stripe Climate Frontier Fund',
    'Grant',
    '$1M-$2M',
    'Global',
    'Annual',
    ARRAY['Carbon removal','Climate'],
    'Carbon removal and climate tech with scientific innovation | Advance market commitment for carbon removal, high bar',
    'https://stripe.com/climate',
    'https://stripe.com/climate/frontier',
    false
  ),
(
    'The Tory Burch Foundation Fellowship',
    'Grant',
    '$5K-$10K + education',
    'US-based',
    'Annual',
    ARRAY['Women founders','Retail','Consumer'],
    'Women entrepreneurs in product-based or retail businesses | Women in retail/consumer products, includes education program',
    'https://www.toryburchfoundation.org/',
    'https://www.toryburchfoundation.org/',
    false
  ),
(
    'UN Global Compact Young SDG Innovators Programme',
    'Accelerator',
    'Free program',
    'Global',
    'Jan 31 2026',
    ARRAY['Sustainable Development Goals (SDGs)'],
    'Young Professionals | 9-month programme, 4 hours/month minimum, 4 1-day workshops, global or in-country tracks',
    'https://unglobalcompact.org/',
    'https://unglobalcompact.org/',
    false
  ),
(
    'Urban-X Accelerator',
    'Accelerator',
    '$150K investment (equity) + program value',
    'NYC, SF, or remote',
    'Bi-annual',
    ARRAY['Smart cities','Urban tech','Climate'],
    'Startups reimagining city life, urban innovation | MINI and Urban.us partnership, takes equity but included for context',
    'https://www.urban-x.com/',
    'https://www.urban-x.com/',
    false
  ),
(
    'VentureWell E-Team Grant',
    'Grant',
    'Phase 1: $5K, Phase 2: $15K',
    'US-based',
    'Annual',
    ARRAY['STEM','DeepTech','Hardware'],
    'University students and recent graduates with STEM innovations | Student and early-career focused, STEM innovations',
    'https://venturewell.org/',
    'https://venturewell.org/e-team/',
    false
  ),
(
    'Ventureneer',
    'Grant',
    '$2K-$10K (varies)',
    'Women founders',
    'Varies',
    ARRAY['Tech','Innovation (women founders)'],
    'Women entrepreneurs in tech and innovation | Multiple grant opportunities aggregated, women-focused',
    'https://www.ventureneer.com/',
    'https://www.ventureneer.com/',
    false
  ),
(
    'ViVE Startup Pitch 2026',
    'Competition',
    'Prize + exposure to health leaders',
    'Global',
    'Feb 22-25 2026',
    ARRAY['Healthtech Digital Health'],
    'Early-stage | Los Angeles, leading event for health and medtech founders, 400+ industry influencers',
    'https://viveevent.com/startup-pitch',
    'https://viveevent.com/startup-pitch',
    false
  ),
(
    'We Pitch Black',
    'Competition',
    'Up to $15k + $40k services',
    'Global',
    'Dec 5, 2026',
    ARRAY['BIPOC/Immigrant/Refugee'],
    'Early-stage | Midwest entrepreneurs, Finale: June 27, 2026',
    'https://wepitchblack.com/',
    'https://wepitchblack.com/',
    false
  ),
(
    'Women''s Startup Lab Accelerator',
    'Accelerator',
    'Program value + pitch opportunities',
    'San Francisco Bay Area',
    'Rolling cohorts',
    ARRAY['Tech (women founders)'],
    'Women founders in tech | Women-focused, takes no equity, pitch competitions',
    'https://www.womenstartuplab.com/',
    'https://www.womenstartuplab.com/',
    false
  ),
(
    'ZenBusiness Startup Grant',
    'Grant',
    '$5000',
    'Global',
    'Dec 31 2025',
    ARRAY['All sectors'],
    'Pre-seed/Seed | Must be ZenBusiness customer, business formed within last 3-6 months, meaningful community impact',
    'https://www.zenbusiness.com/',
    'https://www.zenbusiness.com/',
    false
  ),
(
    'gener8tor Curql Accelerate',
    'Grant',
    'Program + travel',
    'Global',
    'February 2026',
    ARRAY['B2B FinTech'],
    'B2B fintech startups | Kickoff: Feb 12, 2026. Fintech-specific cohort',
    'https://www.gener8tor.com/',
    'https://www.gener8tor.com/accelerators',
    false
  ),
(
    'gener8tor Great Lakes Innovation Accelerator',
    'Grant',
    'Program coverage + travel',
    'Great Lakes region',
    'February 2026',
    ARRAY['Water technology'],
    'Water technology startups in Great Lakes region | Kickoff: Feb 8, 2026. Contact: Soham Dalal',
    'https://www.gener8tor.com/',
    'https://www.gener8tor.com/accelerators',
    false
  );

-- STEP 3: Insert equity funding (90 records)
INSERT INTO funding_opportunities (
  name, opportunity_type, check_size, location, deadline,
  focus_areas, description, website, link, featured
) VALUES
(
    'Jump Capital',
    'VC',
    '$5M-$20M',
    'Chicago',
    'Rolling',
    ARRAY['Fintech','B2B SaaS','Media'],
    'Data-driven tech investor focused on Fintech, IT, B2B SaaS, and Media.',
    'https://jumpcap.com',
    'https://jumpcap.com',
    true
  ),
(
    'The Raise by LongJump',
    'Accelerator',
    '$10K grants',
    'Chicago',
    'Rolling',
    ARRAY['Pre-seed fundraising preparation'],
    '6-part in-person program (Jan 20 - March 11, 2026). 15 founders selected, 5 receive $10K grants. For post-product, pre-pre-seed Chicago founders planning to fundraise spring/summer 2026.',
    'https://longjump.vc',
    'https://tally.so/r/3XKDdg',
    true
  ),
(
    'Capitalize VC',
    'VC',
    NULL,
    'Chicago, IL',
    'Rolling',
    ARRAY['Commerce-enabled Tech'],
    'Chicago',
    'https://airtable.com/apppvODtMSw09eCae/pagCPM2mBqQUDmmmY/form',
    'https://airtable.com/apppvODtMSw09eCae/pagCPM2mBqQUDmmmY/form',
    true
  ),
(
    'Fifth Star Funds',
    'VC',
    '$50K-$250K',
    'Chicago',
    'Rolling',
    ARRAY['B2B SaaS','Underrepresented founders'],
    'Focus on underrepresented founders, B2B/SaaS companies. | Focus on underrepresented founders',
    'https://www.fifthstarfunds.com/',
    'https://www.fifthstarfunds.com/application',
    true
  ),
(
    'LongJump',
    'VC',
    '$100k + services',
    'Chicago, IL',
    'Rolling',
    ARRAY['Industry-agnostic'],
    'Chicago program',
    'https://tally.so/r/3qEA5Y',
    'https://tally.so/r/3qEA5Y',
    true
  ),
(
    'LongJump VC',
    'VC',
    '$10K-$100K',
    'Chicago',
    'Rolling',
    ARRAY['Industry-agnostic','Underrepresented founders'],
    'Pre-seed program focused on underrepresented founders in Chicago. | Focus on underrepresented founders',
    'https://longjump.vc',
    'https://tally.so/r/3qEA5Y',
    true
  ),
(
    'Propellant Ventures',
    'VC',
    '$100k-$500k',
    'Chicago, IL',
    'Rolling',
    ARRAY['B2B: HealthTech','Future of Work','Supply Chain','FinTech','EdTech'],
    'Chicago early-stage',
    'https://www.propellant.vc/',
    'https://www.propellant.vc/',
    true
  ),
(
    'Sandalphon Capital',
    'VC',
    '$100k-$250k (Pre-seed), $500k-$1M (Seed)',
    'Chicago, IL',
    'Rolling',
    ARRAY['Digital Health','InsurTech','FinTech','PropTech','GovTech'],
    'Chicago/Midwest, digital transformation focus',
    'https://sandalphoncapital.com/',
    'https://sandalphoncapital.com/',
    true
  ),
(
    'Abundant Venture Partners',
    'VC',
    NULL,
    'Chicago, IL',
    'Rolling',
    ARRAY['Health/Med','B2B/SaaS'],
    'Chicago',
    'https://www.abundantventurepartners.com/venture-studio/#venture-studio-contact',
    'https://www.abundantventurepartners.com/venture-studio/#venture-studio-contact',
    true
  ),
(
    'CMT Digital',
    'VC',
    '$250K-$5M',
    'Chicago',
    'Rolling',
    ARRAY['Blockchain','Crypto','Web3'],
    'Pre-seed to mid-stage blockchain, crypto, and digital assets investor.',
    'https://cmt.digital',
    'https://cmt.digital',
    true
  ),
(
    'Chingona Ventures',
    'VC',
    '$100K-$500K',
    'Chicago',
    'Rolling',
    ARRAY['Women & minority-led','Consumer','B2B'],
    'Supporting women and minority-led companies and overlooked founders. | Focus on underrepresented founders',
    'https://www.chingona.ventures/',
    'https://www.chingona.ventures/apply',
    true
  ),
(
    'Decasonic',
    'VC',
    '$500K-$3M',
    'Chicago',
    'Rolling',
    ARRAY['Web3','AI','B2B SaaS'],
    'Seed-Series A investor in Web3, AI/Data, and B2B/SaaS.',
    'https://decasonic.com',
    'https://decasonic.typeform.com/businessplans',
    true
  ),
(
    'Harvard Business School Angels - Chicago',
    'VC',
    NULL,
    'Chicago, IL',
    'Rolling',
    ARRAY['Various'],
    'HBS alumni and Chicago startups',
    'https://www.hbsaec.org/',
    'https://www.hbsaec.org/',
    true
  ),
(
    'Long Chicago',
    'VC',
    '$12.5M fund',
    'Chicago, IL',
    'Rolling',
    ARRAY['Local Chicago startups'],
    'Partners with Techstars to revive Techstars Chicago',
    NULL,
    NULL,
    true
  ),
(
    'M25',
    'VC',
    '$250K-$2M',
    'Chicago',
    'Rolling',
    ARRAY['Tech companies (Midwest only)'],
    'Most active investor in Midwest startups. Rolling applications. Focus exclusively on Midwest-headquartered tech companies.',
    'https://www.m25vc.com/',
    'https://www.m25vc.com/',
    true
  ),
(
    'Westbound Equity Partners',
    'VC',
    '$250K-$2M',
    'National',
    'Rolling',
    ARRAY['Black','Latino','Underrepresented founders'],
    'Building Wealth & Opportunity for Black, Latino, and underrepresented founders of color. $100M Fund II. | Focus on underrepresented founders',
    'https://westboundequity.com/',
    'https://westboundequity.com/contact-us/',
    true
  ),
(
    '7wire Ventures',
    'VC',
    '$5M-$15M',
    'Chicago',
    'Rolling',
    ARRAY['Digital health','Healthcare IT'],
    'Healthcare-focused VC investing in digital health, healthcare IT, and services. Most active healthcare investor in Midwest.',
    'https://www.7wireventures.com/',
    'https://www.7wireventures.com/',
    false
  ),
(
    'Arch Venture Partners',
    'VC',
    '$5M-$30M',
    'Chicago',
    'Rolling',
    ARRAY['Life sciences'],
    'Life science VC focused on preventing, detecting, and curing disease.',
    'https://www.archventure.com/',
    'https://www.archventure.com/',
    false
  ),
(
    'BVF (Blue Venture Fund)',
    'VC',
    '$2M-$10M',
    'Chicago',
    'Rolling',
    ARRAY['Life sciences','Biotech'],
    'Life sciences and healthcare technology investor.',
    'https://blueventurefund.com',
    'https://blueventurefund.com',
    false
  ),
(
    'Builders VC',
    'VC',
    '$2M-$10M',
    'Chicago',
    'Rolling',
    ARRAY['Industry transformation','B2B'],
    'Modernizing antiquated industries with technology and innovative solutions.',
    'https://www.builders.vc',
    'https://www.builders.vc',
    false
  ),
(
    'Cultivian Sandbox',
    'VC',
    '$2M-$10M',
    'Chicago',
    'Rolling',
    ARRAY['Food tech','AgTech'],
    'Food and agriculture technology investor.',
    'https://cultiviansbx.com',
    'https://cultiviansbx.com',
    false
  ),
(
    'Energize Capital',
    'VC',
    '$5M-$20M',
    'Chicago',
    'Rolling',
    ARRAY['Climate software','Sustainability'],
    'Climate software and sustainable innovation solutions investor.',
    'https://www.energizecap.com/',
    'https://www.energizecap.com/',
    false
  ),
(
    'PEAK6',
    'VC',
    '$2M-$15M',
    'Chicago',
    'Rolling',
    ARRAY['Consumer tech','Trading tech'],
    'Investment firm building and investing in businesses that ought to be. Focus on consumer tech.',
    'https://peak6.com',
    'https://peak6.com',
    false
  ),
(
    'S2G Investments',
    'VC',
    '$5M-$20M',
    'Chicago',
    'Rolling',
    ARRAY['Food','Agriculture','Sustainability'],
    'Multi-stage VC focused on food, agriculture, and sustainability. $1B+ AUM.',
    'https://www.s2gventures.com/',
    'https://www.s2gventures.com/',
    false
  ),
(
    'Baird Capital',
    'VC',
    NULL,
    'Global',
    'Rolling',
    ARRAY['Software','Healthcare','Consumer','Industrial Tech'],
    'Growth stage',
    'https://www.bairdcapital.com/investment-strategies/venture-capital/',
    'https://www.bairdcapital.com/investment-strategies/venture-capital/',
    false
  ),
(
    'Modern Ventures',
    'VC',
    NULL,
    'Global',
    'Rolling',
    ARRAY['PropTech','InsurTech','FinTech','Real Estate Tech'],
    NULL,
    'https://www.moderneventures.com/',
    'https://www.moderneventures.com/',
    false
  ),
(
    'Duality Accelerator',
    'Accelerator',
    'Grant (prize money)',
    'Chicago',
    'Rolling',
    ARRAY['Underrepresented founders','Impact'],
    'Accelerator focused on diverse founders and underrepresented entrepreneurs. | Focus on underrepresented founders',
    'https://www.dualityaccelerator.com/',
    'https://www.dualityaccelerator.com/',
    false
  ),
(
    'Forum Ventures — Launch Accelerator',
    'Accelerator',
    '$150K investment',
    'Global',
    'Rolling',
    ARRAY['B2B SaaS','Marketplace','FinTech'],
    'B2B SaaS, Marketplace, and Fintech accelerator program.',
    'https://www.launch.co/',
    'https://www.launch.co/',
    false
  ),
(
    'Techstars Chicago',
    'Accelerator',
    '$20K + $100K convertible',
    'Chicago',
    'Rolling',
    ARRAY['Industry-agnostic','High-growth'],
    'In-person accelerator program providing funding, mentorship, and network access.',
    'https://www.techstars.com/',
    'https://www.techstars.com/accelerators/chicago',
    false
  ),
(
    'Techstars Healthcare (Northwestern Medicine)',
    'Accelerator',
    '$20K + $100K convertible',
    'Chicago',
    'Rolling',
    ARRAY['Healthcare'],
    'Healthcare-specific Techstars program in partnership with Northwestern Medicine.',
    'https://www.techstars.com/',
    'https://www.techstars.com/accelerators/healthcare',
    false
  ),
(
    'mHUB Hardtech Accelerator',
    'Accelerator',
    'Varies',
    'Chicago',
    'Rolling',
    ARRAY['MedTech','Smart Manufacturing','EnergyTech'],
    'MedTech, Smart Manufacturing, and EnergyTech cohorts for hardtech startups.',
    'https://mhubchicago.com/',
    'https://mhubchicago.com/',
    false
  ),
(
    'mPOWER by mHUB',
    'Accelerator',
    '$50K grants',
    'Chicago',
    'Rolling',
    ARRAY['Hardtech','DeepTech'],
    'Grant program for early-stage hardtech and deeptech startups.',
    'https://mhubchicago.com/',
    'https://mhubchicago.com/mpower/',
    false
  ),
(
    '2048 Ventures',
    'VC',
    '$250k-$750k',
    'Global',
    'Rolling',
    ARRAY['AI/Data','B2B/SaaS','Hardtech'],
    NULL,
    'https://airtable.com/appV89PYGo3zN47f9/pagNjeYwHGDSGIs3/form',
    'https://airtable.com/appV89PYGo3zN47f9/pagNjeYwHGDSGIs3/form',
    false
  ),
(
    'Angeles Investors',
    'VC',
    '$25K-$100K',
    'Global',
    'Rolling',
    ARRAY['Latino/Latina founders'],
    'Focus on Latino/Latina founders. | Focus on underrepresented founders',
    'https://angelesinvestors.com/',
    'https://angelesinvestors.com/startupsapplication/',
    false
  ),
(
    'Beta Boom',
    'VC',
    '$350k-$500k',
    'Global',
    'Rolling',
    ARRAY['Software'],
    'Founders who defy Silicon Valley mold',
    'https://www.betaboom.com/apply',
    'https://www.betaboom.com/apply',
    false
  ),
(
    'Hyde Park Angels',
    'VC',
    '$25K-$250K',
    'Chicago',
    'Rolling',
    ARRAY['Industry-agnostic'],
    'Largest angel group in Midwest with 100+ members.',
    'https://hydeparkangels.com',
    'https://hydeparkangels.com/',
    false
  ),
(
    'Lightship Capital',
    'VC',
    '$100K-$500K',
    'Cincinnati',
    'Rolling',
    ARRAY['B2B SaaS'],
    'Pre-seed B2B/SaaS investor.',
    'https://www.lightship.capital/',
    'https://www.lightship.capital/apply',
    false
  ),
(
    'Next Chapter Ventures',
    'VC',
    NULL,
    'Global',
    'Rolling',
    ARRAY['Scalable business models'],
    NULL,
    'https://www.ncvinvestments.com/founders',
    'https://www.ncvinvestments.com/founders',
    false
  ),
(
    'Plug and Play Tech Center',
    'VC',
    'Varies',
    'Sunnyvale',
    'Rolling',
    ARRAY['AgriTech','Energy','FinTech','Health','DeepTech'],
    'Global innovation platform and accelerator across multiple verticals.',
    'https://www.plugandplaytechcenter.com/',
    'https://www.plugandplaytechcenter.com/',
    false
  ),
(
    'Serra Ventures',
    'VC',
    '$250K-$3M',
    'Champaign',
    'Rolling',
    ARRAY['Midwest tech','B2B'],
    'Early-stage investor in Midwest technology companies.',
    'https://www.serraventures.com/',
    'https://www.serraventures.com/',
    false
  ),
(
    'Solanus Capital Partners',
    'VC',
    '$5M fund',
    'Global',
    'Rolling',
    ARRAY['Sector-agnostic'],
    'Focus on grit, tenacity, domain expertise',
    NULL,
    NULL,
    false
  ),
(
    'Y Combinator',
    'VC',
    '$500K (2024 batch)',
    'Mountain View',
    'Rolling',
    ARRAY['Industry-agnostic','High-growth'],
    'World''s leading startup accelerator. Provides funding, mentorship, and network. 2 cohorts per year.',
    'https://www.ycombinator.com/',
    'https://www.ycombinator.com/apply',
    false
  ),
(
    '53 Stations',
    'VC',
    '$500K-$5M',
    'Chicago',
    'Rolling',
    ARRAY['AI','Enterprise','Logistics','HealthTech','FinTech'],
    'Seed to Series B in tech-forward companies across AI, enterprise software, logistics, healthtech, fintech.',
    'https://www.53stations.com/',
    'https://www.53stations.com/',
    false
  ),
(
    'Barrel Ventures',
    'VC',
    '$500K-$5M',
    'Chicago',
    'Rolling',
    ARRAY['Food & Beverage','CPG'],
    'Seed and Series A investments in food & beverage and consumer CPG.',
    'https://www.barrelvc.com/',
    'https://www.barrelvc.com/',
    false
  ),
(
    'Bluestein Ventures',
    'VC',
    '$500K-$3M',
    'Chicago',
    'Rolling',
    ARRAY['Food tech','CPG','F&B'],
    'Food tech VC investing in future of food, foodtech, B2C and B2B food brands. $45M Fund III.',
    'https://bluesteinventures.com',
    'https://bluesteinventures.com',
    false
  ),
(
    'Bridge Venture Fund',
    'VC',
    '$250K-$2M',
    'Midwest',
    'Rolling',
    ARRAY['Midwest tech','Early-stage'],
    'Early-stage technology companies in the Midwest.',
    'https://www.bridgeventurefund.com/',
    'https://www.bridgeventurefund.com/',
    false
  ),
(
    'CIC Angels',
    'VC',
    NULL,
    'Global',
    'Rolling',
    ARRAY['Various'],
    NULL,
    'https://www.cicangels.com/',
    'https://www.cicangels.com/',
    false
  ),
(
    'Chicago Arch Angels',
    'VC',
    '$25K-$250K',
    'Chicago',
    'Rolling',
    ARRAY['Early-stage tech'],
    'Angel investment group focused on early-stage companies.',
    'https://www.chicagoarchangels.com/',
    'https://www.chicagoarchangels.com/',
    false
  ),
(
    'Chicago Ventures',
    'VC',
    '$500K-$5M',
    'Chicago',
    'Rolling',
    ARRAY['B2B SaaS','Marketplace','Enterprise'],
    'Early-stage VC empowering founders to build enduring companies. Lead early rounds with operational support.',
    'https://chicagoventures.com',
    'https://chicagoventures.com/',
    false
  ),
(
    'Cornerstone Angels',
    'VC',
    NULL,
    'Global',
    'Rolling',
    ARRAY['Various'],
    NULL,
    'https://www.cornerstoneangels.com/',
    'https://www.cornerstoneangels.com/',
    false
  ),
(
    'Drive Capital',
    'VC',
    '$1M-$5M',
    'Columbus',
    'Rolling',
    ARRAY['B2B SaaS','Healthcare'],
    'B2B/SaaS and Health/Med focus with strong Midwest presence.',
    'https://www.drivecapital.com/',
    'https://form.fillout.com/t/aT3BECVJE9us',
    false
  ),
(
    'Earth Foundry',
    'VC',
    '$250K-$2M',
    'Chicago',
    'Rolling',
    ARRAY['Climate tech','Clean energy'],
    'Climate solutions venture studio and fund focusing on clean energy and sustainability.',
    'https://www.earthfoundry.com/',
    'https://www.earthfoundry.com/connect/startup',
    false
  ),
(
    'Elevate Ventures',
    'VC',
    '$100K-$2M',
    'Indiana',
    'Rolling',
    ARRAY['Indiana startups'],
    'Multiple funds & programs for Indiana-based startups.',
    'https://elevateventures.com/',
    'https://elevateventures.com/apply/',
    false
  ),
(
    'Gaingels',
    'VC',
    '$50K-$500K',
    'National',
    'Rolling',
    ARRAY['LGBTQ+ founders & allies'],
    'LGBTQ+ investment network with 10,000+ members backing high-growth startups. | Focus on underrepresented founders',
    'https://www.gaingels.com/',
    'https://www.gaingels.com/',
    false
  ),
(
    'Golden Seeds - Chicago Chapter',
    'VC',
    NULL,
    'Global',
    'Rolling',
    ARRAY['Women-led startups'],
    'Focus on female founders',
    NULL,
    NULL,
    false
  ),
(
    'HBS Alumni Angels Chicago',
    'VC',
    '$25K-$200K',
    'Chicago',
    'Rolling',
    ARRAY['HBS-connected startups'],
    'Harvard Business School alumni angel investment group.',
    'https://www.hbsangels.com/',
    'https://www.hbsangels.com/',
    false
  ),
(
    'Heartland Angels',
    'VC',
    NULL,
    'Global',
    'Rolling',
    ARRAY['Midwest startups'],
    NULL,
    'https://www.heartlandangels.com/',
    'https://www.heartlandangels.com/',
    false
  ),
(
    'High Alpha',
    'VC',
    '$500K-$3M',
    'Indianapolis',
    'Rolling',
    ARRAY['B2B SaaS'],
    'B2B SaaS venture studio and seed investor.',
    'https://www.highalpha.com/',
    'https://www.highalpha.com/get-in-touch',
    false
  ),
(
    'HighVista Venture Capital Fund XIV',
    'VC',
    '$270M raised',
    'Global',
    'Rolling',
    ARRAY['Early-stage venture fund managers'],
    'Exceeded $200M target, focuses on hard-to-access markets',
    NULL,
    NULL,
    false
  ),
(
    'Hustle Fund Chicago',
    'VC',
    '$25K-$250K',
    'Chicago',
    'Rolling',
    ARRAY['Underrepresented founders'],
    'Pre-seed fund focused on underrepresented founders. | Focus on underrepresented founders',
    'https://www.hustlefund.vc/',
    'https://www.hustlefund.vc/',
    false
  ),
(
    'Hyde Park Venture Partners',
    'VC',
    '$500K-$3M',
    'Chicago',
    'Rolling',
    ARRAY['High-growth tech','B2B'],
    'Pre-seed through early Series A investments in high-growth technology startups.',
    'https://www.hydeparkvp.com/',
    'https://www.hydeparkvp.com/',
    false
  ),
(
    'Illini Angels',
    'VC',
    '$25K-$150K',
    'Illinois',
    'Rolling',
    ARRAY['UIUC-connected startups'],
    'University of Illinois alumni angel investment group.',
    'https://www.illiniangels.com/',
    'https://www.illiniangels.com/',
    false
  ),
(
    'Illinois Ventures',
    'VC',
    '$250K-$2M',
    'Champaign',
    'Rolling',
    ARRAY['DeepTech','UIUC-connected'],
    'Investing in University of Illinois deep tech startups. 20+ years, strong alumni network.',
    'https://illinoisventures.com',
    'https://illinoisventures.com',
    false
  ),
(
    'IrishAngels',
    'VC',
    '$25K-$150K',
    'Chicago',
    'Rolling',
    ARRAY['Notre Dame-connected'],
    'Notre Dame alumni angel investment group.',
    'https://irishangels.com/',
    'https://irishangels.com/',
    false
  ),
(
    'JumpStart Ventures',
    'VC',
    '$500K-$3M',
    'Cleveland',
    'Rolling',
    ARRAY['Healthcare','Tech services'],
    'Healthcare and tech-enabled services. Northeast Ohio focus with national reach.',
    'https://jumpstart.vc/',
    'https://jumpstart.vc/funds/#apply',
    false
  ),
(
    'Kapor Capital',
    'VC',
    '$500K-$2M',
    'Oakland',
    'Rolling',
    ARRAY['Gap-closing tech'],
    'Invests in companies solving problems in underrepresented communities (gap-closing tech). | Focus on underrepresented founders',
    'https://www.kaporcapital.com/',
    'https://www.kaporcapital.com/pitch/',
    false
  ),
(
    'Lightbank',
    'VC',
    '$500K-$5M',
    'Chicago',
    'Rolling',
    ARRAY['High-growth tech','Consumer'],
    'Chicago VC founded by Groupon co-founders Brad Keywell & Eric Lefkofsky.',
    'https://www.lightbank.com/',
    'https://www.lightbank.com/',
    false
  ),
(
    'Listen Ventures',
    'VC',
    '$500K-$2M',
    'Chicago',
    'Rolling',
    ARRAY['Consumer','D2C','Wellness','Food & Beverage'],
    'Most active investor in Midwest. Consumer brands, D2C, Wellness, Food & Beverage focus.',
    'https://www.listen.co',
    'https://www.listen.co',
    false
  ),
(
    'Lofty Ventures',
    'VC',
    NULL,
    'Global',
    'Rolling',
    ARRAY['Various'],
    NULL,
    'https://www.loftyventures.com/',
    'https://www.loftyventures.com/',
    false
  ),
(
    'MD Angels',
    'VC',
    NULL,
    'Global',
    'Rolling',
    ARRAY['Healthcare','Medical'],
    NULL,
    'https://www.mdangels.com/',
    'https://www.mdangels.com/',
    false
  ),
(
    'Moderne Ventures',
    'VC',
    '$500K-$5M',
    'Chicago',
    'Rolling',
    ARRAY['PropTech','InsurTech','FinTech'],
    'Strategic VC investing in PropTech, InsurTech, FinTech, Real Estate Tech.',
    'https://www.moderneventures.com/',
    'https://www.moderneventures.com/',
    false
  ),
(
    'Next Coast Ventures',
    'VC',
    '$250K-$2M',
    'Ann Arbor',
    'Rolling',
    ARRAY['Midwest B2B SaaS'],
    'Midwest B2B software companies. Strong Great Lakes region focus.',
    'https://www.nextcoast.vc/',
    'https://www.nextcoast.vc/',
    false
  ),
(
    'Nomadic Venture Partners',
    'VC',
    '$500K-$2M',
    'Chicago',
    'Rolling',
    ARRAY['Climate','Energy','Ag','Food'],
    'Climate/Energy and Ag/Food technology investor.',
    'https://nomadicvp.com',
    'https://nomadicvp.com/pitch/',
    false
  ),
(
    'OCA Ventures',
    'VC',
    '$1M-$5M',
    'National',
    'Rolling',
    ARRAY['Tech','Scalable services'],
    'Tech and scalable services with dramatic growth potential. US and Canada only.',
    'https://www.ocaventures.com/',
    'https://www.ocaventures.com/',
    false
  ),
(
    'Origin Ventures',
    'VC',
    '$1M-$5M',
    'Chicago',
    'Rolling',
    ARRAY['Marketplace','Software','Consumer'],
    'Marketplace, Software, Consumer services focus (Digital Native Economy).',
    'https://www.originventures.com/',
    'https://www.originventures.com/',
    false
  ),
(
    'Origin Ventures Fund VI',
    'VC',
    '$140M raised',
    'Global',
    'Rolling',
    ARRAY['AI','Defense','Frontier Tech'],
    'Expanding into deep-tech',
    'https://www.originventures.com/',
    'https://www.originventures.com/',
    false
  ),
(
    'PACE Healthcare Capital',
    'VC',
    '$500K-$5M',
    'Chicago',
    'Rolling',
    ARRAY['Digital health','Health IT'],
    'Early-stage healthcare VC focused on digital health, health IT, and healthcare services.',
    'https://www.pacehealthcapital.com/',
    'https://www.pacehealthcapital.com/',
    false
  ),
(
    'Pritzker Group',
    'VC',
    '$1M-$10M',
    'Chicago',
    'Rolling',
    ARRAY['SaaS','Marketplace','Consumer'],
    'Venture capital firm focused on SaaS, marketplace, and middle market companies.',
    'https://www.pritzkergroup.com/',
    'https://www.pritzkergroup.com/',
    false
  ),
(
    'Redbud VC',
    'VC',
    '$250K-$2M',
    'Madison',
    'Rolling',
    ARRAY['B2B','AgTech','Industrial'],
    'Midwest B2B software, agtech, and industrial technology.',
    'https://www.redbudvc.com/',
    'https://www.redbudvc.com/',
    false
  ),
(
    'Sandbox Industries',
    'VC',
    '$1M-$10M',
    'Chicago',
    'Rolling',
    ARRAY['Healthcare','Insurance','Food & Ag'],
    'VC investing in healthcare, insurance, and food & agriculture innovation.',
    'https://sandboxindustries.com',
    'https://sandboxindustries.com',
    false
  ),
(
    'Shore Capital Partners Fund VI & II',
    'VC',
    '$850M raised',
    'Global',
    'Rolling',
    ARRAY['Healthcare','Search Funds'],
    '$625M Healthcare Fund VI, $5M-$200M revenue companies',
    NULL,
    NULL,
    false
  ),
(
    'Starting Line',
    'VC',
    '$250K-$1M',
    'Chicago',
    'Rolling',
    ARRAY['Consumer for the 99%'],
    'Consumer VC for ''99% economy'' - democratizing access. $30M Fund II.',
    'https://www.startingline.vc/',
    'https://www.startingline.vc/',
    false
  ),
(
    'Supply Change Capital',
    'VC',
    '$250K-$2M',
    'Chicago',
    'Rolling',
    ARRAY['Ag/Food','Diverse founders'],
    'Ag/Food focus targeting diverse founders with food/ag traction. | Focus on underrepresented founders',
    'https://www.supplychangecapital.com/',
    'https://airtable.com/appcPEhgoZp7mwcGB/shr2lTUpKOh33cajh',
    false
  ),
(
    'Tawani Ventures',
    'VC',
    NULL,
    'Global',
    'Rolling',
    ARRAY['Defense','Aerospace','Dual-use Tech'],
    NULL,
    'https://tawaniventures.com/',
    'https://tawaniventures.com/',
    false
  ),
(
    'The Josephine Collective',
    'VC',
    NULL,
    'Global',
    'Rolling',
    ARRAY['Various'],
    NULL,
    'https://joinjosephine.com/',
    'https://joinjosephine.com/',
    false
  ),
(
    'VamosVentures',
    'VC',
    '$100K-$500K',
    'National',
    'Rolling',
    ARRAY['Latinx founders','Latino communities'],
    'Investment fund supporting Latinx founders and startups serving Latino communities. | Focus on underrepresented founders',
    'https://www.vamosventures.com/',
    'https://www.vamosventures.com/',
    false
  ),
(
    'Vitalize Angels',
    'VC',
    NULL,
    'Global',
    'Rolling',
    ARRAY['Various'],
    NULL,
    'https://www.vitalizeangels.com/',
    'https://www.vitalizeangels.com/',
    false
  ),
(
    'West Suburban Angels Inc.',
    'VC',
    NULL,
    'Global',
    'Rolling',
    ARRAY['Chicago suburban startups'],
    NULL,
    'https://www.westsuburbanangels.com/',
    'https://www.westsuburbanangels.com/',
    false
  ),
(
    'a11y Capital',
    'VC',
    '$100K-$1M',
    'National',
    'Rolling',
    ARRAY['Accessibility','Disability inclusion'],
    'Supporting startups building accessible products for people with disabilities. | Focus on underrepresented founders',
    'https://www.a11ycapital.com/',
    'https://www.a11ycapital.com/',
    false
  ),
(
    'mHUB Spark Fund II',
    'VC',
    '$20M target',
    'Global',
    'Rolling',
    ARRAY['Hardtech','Physical Products'],
    'Energy, medtech, manufacturing, 65 startups over 4 years',
    NULL,
    NULL,
    false
  );

-- STEP 5: Verify import
SELECT opportunity_type, COUNT(*) FROM funding_opportunities GROUP BY opportunity_type ORDER BY opportunity_type;
SELECT COUNT(*) as total FROM funding_opportunities;
